### ISSUE TITLE
What about a GDTF-file?

### ISSUE THREAD

**Issue by Skutla** [Chauvet-Pro/ROGUEOUTCAST2XWASH#1]
I´ve been searching for a new fixture file to go with your new firmware. I´m currently using the 23 ch mode. Why can't I find any GDTF-files on www.gdtf-share.com ? I am of the impression that it´s supposed to be the fixture manufacturer that provides this common fixture file....not the console manufacturer....

**Comment by dgooch5200** [comment]
@Skutla We will have an updated GDFT file up as soon as we can, and thank you for letting us know.

**Comment by dgooch5200** [comment]
@Skutla An updated GDTF profile has been added to the gdtf-share.
